### ISSUE TITLE
plugin broken with current master of Jekyll

### ISSUE THREAD

**Issue by rriemann** [envygeeks/jekyll-cache#2]
When upgrading to Jekyll master (rev: https://github.com/jekyll/jekyll/commit/68e633a56ec712acde4b2527b6f00125b419997a), then this plugin produces an error:

```
bundle exec jekyll s --watch --incremental                                                                                       rriemann@mars
WARNING: Nokogiri was built against LibXML version 2.9.8, but has dynamically loaded 2.9.9
/home/rriemann/.rvm/gems/ruby-2.4.3/gems/jekyll-cache-1.2.0/lib/jekyll-cache.rb:11:in `<module:Jekyll>': Cache is not a module (TypeError)
        from /home/rriemann/.rvm/gems/ruby-2.4.3/gems/jekyll-cache-1.2.0/lib/jekyll-cache.rb:10:in `<top (required)>'
        from /home/rriemann/.rvm/gems/ruby-2.4.3/gems/jekyll-flickr-0.1.1/lib/jekyll-flickr/flickr_tag.rb:4:in `require'
        from /home/rriemann/.rvm/gems/ruby-2.4.3/gems/jekyll-flickr-0.1.1/lib/jekyll-flickr/flickr_tag.rb:4:in `<top (required)>'

```

The error comes from:

```ruby
cache = Jekyll::Cache::FileStore.new 'flickr'
```

The reason is that Jekyll has changed how the cache works:

- https://github.com/jekyll/jekyll/commits/55f0980716a2f3a032bdb1c578518d5f21230e4a/lib/jekyll/cache.rb
- https://github.com/jekyll/jekyll/pull/7169
- docs: https://github.com/jekyll/jekyll/blob/master/docs/_tutorials/cache_api.md

**Comment by envygeeks** [comment]
The error you are getting likely stems from a system build problem.  `libxml2` and wherever you compiled `nokogiri` needs to be rebuilt.

**Comment by rriemann** [comment]
The XML warning is just a warning and I have it for a long time already.

I fixed the problem already by:

- removing your plugin
- using `Jeyll:Cache.new` insteald of `Jekyll::Cache::FileStore.new`
- and changing from `#fetch` to `#getset`

**Comment by envygeeks** [comment]
My gem has existed since well before Jekyll came around and made their own caching using an interface that is non-standard to most RubyGems.  I also use ActiveSupport::Cache which has existed also long before Jekyll created their diverging interface for caching.

I have no plans to change my interfaces to suite Jekyll.

Thanks!
